### ISSUE TITLE
Nbextensions tab not appearing on dashboard when using docker and jupyter notebook image

### ISSUE THREAD

**Issue by wee-analyze** [Jupyter-contrib/jupyter_nbextensions_configurator#115]
I'm using a jupyter notebook image in a docker container and I don't get a nbextension tab in the dashboard after I refresh the page. The extensions are working though when I do a jupyter subcommand such as 

`jupyter nbextension enable codefolding/main`

I run the docker with this command in my terminal 
`docker run --rm -p 8888:8888 -v /Users/me/Desktop/project:/home/jovyan/ jupyter/tensorflow-notebook`

I open the jupyter notebook and run these in a cell
`!pip install jupyter_contrib_nbextensions`
`!jupyter contrib nbextension install --user`
`!pip install jupyter_nbextensions_configurator`
`!jupyter nbextensions_configurator enable --user`

I refresh the home page but the tab never appears. Am I missing something?

**Comment by gothicVI** [comment]
```bash
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
pip install jupyter_nbextensions_configurator
jupyter nbextensions_configurator enable --user
```
These commands are meant to be run from the command line.
It could be that a running notebook session locks some files they would alter. I'd thus not recommend running them from within a notebook.

**Comment by wee-analyze** [comment]
Thanks for the reply. Yes, I was able to resolve this by placing the commands in the dockerfile instead.
