### ISSUE TITLE
Empty configurator

### ISSUE THREAD

**Issue by tbrodbeck** [Jupyter-contrib/jupyter_nbextensions_configurator#119]
![Screenshot 2020-07-08 at 14 12 24](https://user-images.githubusercontent.com/24418160/86917304-27913580-c125-11ea-989b-720647c40c7f.png)
I am not sure. Am I doing something wrong? I installed it without conda

**Comment by fhennig** [comment]
I installed it once in conda, once without, doesn't work either way.

The version is 0.4.1

python 3.8.2

**Comment by tbrodbeck** [comment]
Ah thank you, now it works 👍
