### ISSUE TITLE
The library dependency `mathjaxutils` has moved in newer releases of jupyter notebook 6.x.x

### ISSUE THREAD

**Issue by takato1314** [Jupyter-contrib/jupyter_nbextensions_configurator#125]
Currently, I am using Jupyter Notebook 6.1.6 with [nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions). While opening the notebook page, I face the following issues complaining that the `mathjaxutils` is not found.
![image](https://user-images.githubusercontent.com/10910968/103401549-3a407080-4b84-11eb-8197-f2e41851be14.png)

After some investigations, it is found that the Jupyter Notebook developers has moved the `mathjaxutils.js` file from `static/notebook/js/mathjaxutils` to `static/base/js/mathjaxutils.js` from this [commit](https://github.com/jupyter/notebook/commit/cba497548c4c9f2de21edf6be6cc4d56480fc222#diff-0117cf1e39412cca6ccf4f1c435a803b4568e8a2a4326fcb06d740300ea4025d).

Due to this change, the configurator also need to change the from the old path `notebook/js/mathjaxutils` to `base/js/mathjaxutils.js`  to load the dependency correctly:
![image](https://user-images.githubusercontent.com/10910968/103401684-cce10f80-4b84-11eb-9927-2163996e3098.png)

**Comment by Ubisoft-potato** [comment]
@takato1314 I tried your solution , and i change the `Render.js` file's `notebook/js/mathjaxutils`  to `base/js/mathjaxutils`  finally solve  the problem , Thanks!

**Comment by takato1314** [comment]
You're welcome. Glad that solved your problem too.

**Comment by vinfun** [comment]
> @takato1314 I tried your solution , and i change the `Render.js` file's `notebook/js/mathjaxutils` to `base/js/mathjaxutils` finally solve the problem , Thanks!

It's also work for me. Thanks a lot.

**Comment by vinfun** [comment]
> You're welcome. Glad that solved your problem too.

Refer to wrong man. Thanks.

**Comment by amod400** [comment]
you can find your `render.js` using `find . -name render.js` and update which is relevant

**Comment by Oleg-dM** [comment]
on Windows, found render.js in
`AppData\Local\Programs\Python\Python38\Lib\site-packages\jupyter_nbextensions_configurator\static\nbextensions_configurator\render`

made the change and it worked!

**Comment by chebee7i** [comment]
Ping? Can we get this integrated?

**Comment by jizhihaoSAMA** [comment]
Oh, I'm stuck here one day! This is the first time I use Jupyter Notebook.Because of this ,I can't use extension.

**Comment by takato1314** [comment]
Just create a quick PR to get this merged, hopefully there are still people here who can help to merge the PR.

**Comment by Zsailer** [comment]
This issue should be fixed in `notebook>=6.2.0`, thanks to jupyter/notebook#5934.

**Comment by takato1314** [comment]
Ok i will close my PR then since it was not needed anymore with the fix above.

**Comment by Olave** [comment]
It's also work for me. Thanks a lot.

**Comment by ebabak** [comment]
> on Windows, found render.js in `AppData\Local\Programs\Python\Python38\Lib\site-packages\jupyter_nbextensions_configurator\static\nbextensions_configurator\render`
> 
> made the change and it worked!

Hi, I'm fairly new to Jupyter. What exactly I should do(windows) should I copy this file somewhere?
Thank you
