### ISSUE TITLE
localhost:8888/nbextensions/ is blank

### ISSUE THREAD

**Issue by ElLorans** [Jupyter-contrib/jupyter_nbextensions_configurator#126]
On a new conda env, I insert
`conda install -c conda-forge jupyter_contrib_nbextension`
If I close the anaconda prompt, launch it again and open Jupyter Notebook, I don't see the extensions page. If I open it from a .ipynb using the EDIT menu, I get to localhost:8888/nbextensions/ which is blank. Is it possible that the JQuery fails to load or that nbextensions do not work with notebook 6.1?

My env:

```
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py39hb82d6ee_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py39hcbf5309_0    conda-forge
cffi                      1.14.4           py39h0878f49_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
importlib-metadata        3.3.0            py39hcbf5309_2    conda-forge
importlib_metadata        3.3.0                hd8ed1ab_2    conda-forge
ipykernel                 5.4.2            py39he1a07ef_0    conda-forge
ipython                   7.19.0           py39h832f523_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py39hcbf5309_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1            py39hde42818_1    conda-forge
jupyter_core              4.7.0            py39hcbf5309_0    conda-forge
jupyter_highlight_selected_word 0.2.0           py39hde42818_1002    conda-forge
jupyter_latex_envs        1.4.6           py39hde42818_1001    conda-forge
jupyter_nbextensions_configurator 0.4.1            py39hde42818_2    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libxml2                   2.9.10               hf5bbc77_3    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
lxml                      4.6.2            py39h4fd7cdf_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                1.1.1            py39ha3862ff_2    conda-forge
mistune                   0.8.4           py39hb82d6ee_1002    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py39hcbf5309_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
notebook                  6.1.6            py39hcbf5309_0    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandoc                    2.11.3.2             h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py39hb82d6ee_1    conda-forge
python                    3.9.1           h7840368_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pywin32                   228              py39h4cdbadb_0    conda-forge
pywinpty                  0.5.7            py39hde42818_1    conda-forge
pyyaml                    5.3.1            py39ha3862ff_1    conda-forge
pyzmq                     20.0.0           py39h6e08c89_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py39h467e6f4_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
terminado                 0.9.2            py39hcbf5309_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tornado                   6.1              py39hb82d6ee_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tzdata                    2020f                he74cb21_0    conda-forge
vc                        14.2                 hb210afc_2    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py39hde42818_1005    conda-forge
winpty                    0.4.3                         4    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.3                h0e60522_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
```

**Comment by MarcosBrum** [comment]
Same issue here.

**Comment by ElLorans** [comment]
Same problem with pip: on a new conda env, I do `pip install jupyter_contrib_nbextensions` and then `jupyter contrib nbextension install --sys-prefix`.

My env:
`# Name                    Version                   Build  Channel
argon2-cffi               20.1.0                   pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bleach                    3.2.1                    pypi_0    pypi
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py38haa244fe_0    conda-forge
cffi                      1.14.4                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
ipykernel                 5.4.2                    pypi_0    pypi
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
jupyter-core              4.7.0                    pypi_0    pypi
jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
jupyter-latex-envs        1.4.6                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
lxml                      4.6.2                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
nbclient                  0.5.1                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.0.8                    pypi_0    pypi
nest-asyncio              1.4.3                    pypi_0    pypi
notebook                  6.1.6                    pypi_0    pypi
openssl                   1.1.1i               h8ffe710_0    conda-forge
packaging                 20.8                     pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
prometheus-client         0.9.0                    pypi_0    pypi
prompt-toolkit            3.0.9                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.7.3                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
python                    3.8.6           h7840368_4_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pywin32                   300                      pypi_0    pypi
pywinpty                  0.5.7                    pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0                   pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                49.6.0           py38h9bdc248_2    conda-forge
six                       1.15.0                   pypi_0    pypi
sqlite                    3.34.0               h8ffe710_0    conda-forge
terminado                 0.9.2                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
vc                        14.2                 hb210afc_2    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py38h32f6830_1005    conda-forge`

**Comment by wissam124** [comment]
Hi all,

I have the exact same issue today after a fresh install of jupyter and jupyter_contrib_nbextensions through pip.
<http://localhost:8888/nbextensions> returns a blank tab

Extensions are still loaded properly though if I a manually edit the file **jupyter_notebook_config.json**
or use ```jupyter nbextension enable``` to manually install an extension.

Here's my jupyter config if that helps:
```console
$ jupyter --version
jupyter core     : 4.7.0
jupyter-notebook : 6.1.6
qtconsole        : not installed
ipython          : 7.19.0
ipykernel        : 5.4.2
jupyter client   : 6.1.7
jupyter lab      : 3.0.1
nbconvert        : 5.6.1
ipywidgets       : 7.6.2
nbformat         : 5.0.8
traitlets        : 5.0.5
```

**Comment by jeffyjefflabs** [comment]
Everyone here has notebook 6.1.6 in their conda listing, so I'm guessing this is the same issue as #125.

**Comment by MarcosBrum** [comment]
A solved the problem downgrading the notebook to version 5.6.0, using pip.

**Comment by ElLorans** [comment]
I confirm that using `conda install notebook 5.6.0` and then `conda install -c conda-forge jupyter_contrib_nbextension` solves the issue. You will need to downgrade to python <= 3.7.9 .

**Comment by jeffyjefflabs** [comment]
You only need to go back to notebook 6.1.5, if that saves you the trouble of downgrading python too.

**Comment by MarcosBrum** [comment]
I'm using notebook version 5.6.0 and Python version 3.8.5.

**Comment by ElLorans** [comment]
@jeffyjefflabs that works and is the best solution, thank you

**Comment by XiaoYangsCode** [comment]
> You only need to go back to notebook 6.1.5, if that saves you the trouble of downgrading python too.

thanks,it`s work

**Comment by lukefeilberg** [comment]
A heads up I'm getting this same issue with notebook version 6.5.3.

```cmd
>jupyter --version
Selected Jupyter core packages...
IPython          : 8.10.0
ipykernel        : 6.19.2
ipywidgets       : 8.0.4
jupyter_client   : 7.4.9
jupyter_core     : 5.3.0
jupyter_server   : 1.23.4
jupyterlab       : 3.5.3
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.7.0
notebook         : 6.5.3
qtconsole        : 5.4.0
traitlets        : 5.7.1
```

I just downgraded to 6.1.5 and it worked as well.

**Comment by sebastianstegmaier** [comment]
> A heads up I'm getting this same issue with notebook version 6.5.3.
> 
> ```batchfile
> >jupyter --version
> Selected Jupyter core packages...
> IPython          : 8.10.0
> ipykernel        : 6.19.2
> ipywidgets       : 8.0.4
> jupyter_client   : 7.4.9
> jupyter_core     : 5.3.0
> jupyter_server   : 1.23.4
> jupyterlab       : 3.5.3
> nbclient         : 0.5.13
> nbconvert        : 6.5.4
> nbformat         : 5.7.0
> notebook         : 6.5.3
> qtconsole        : 5.4.0
> traitlets        : 5.7.1
> ```
> 
> I just downgraded to 6.1.5 and it worked as well.

Still the same issue and I hope temp solution, I had notebook 7.2
