### ISSUE TITLE
src subdirectory ?

### ISSUE THREAD

**Issue by juhasch** [Jupyter-contrib/jupyter_nbextensions_configurator#2]
Happy to see this as an individual repository. Great work @jcb91 !

One question:
Would it not be better to have the `jupyter_nbextensions_configurator` directly at module level instead at behind `src/jupyter_nbextensions_configurator` ?

**Comment by juhasch** [comment]
Ah, I have seen your comments regarding this in anhttps://github.com/ipython-contrib/IPython-notebook-extensions/pull/634
Closing.
For reference, see https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

**Comment by jcb91** [comment]
Yep, exactly, good spot!
