### ISSUE TITLE
cannot see jupyter nbextension configurator tab

### ISSUE THREAD

**Issue by yunqu** [Jupyter-contrib/jupyter_nbextensions_configurator#72]
I am able to use the URL to access the configurator tab (meaning that everything is installed properly?), but I cannot see the configurator tab in my jupyter:
<img width="1000" alt="1" src="https://user-images.githubusercontent.com/14114006/42181905-5edf8966-7df1-11e8-8ee4-c9867e5a401b.PNG">
<img width="385" alt="2" src="https://user-images.githubusercontent.com/14114006/42181909-60a6c502-7df1-11e8-8c25-618ab8a369ff.PNG">

```shell
# pip3 freeze | grep jupyter
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
```

I have tried reinstall jupyter nbextension as well as the configurator again, but still not working. Any idea?

**Comment by xappppp** [comment]
Same here

**Comment by zhiruiwang** [comment]
My configurator tab also disappeared...

**Comment by zhiruiwang** [comment]
My configurator tab also disappeared recently, but after re-executing
```
jupyter nbextensions_configurator enable --user
```
it will show up again.

**Comment by yunqu** [comment]
@zhiruiwang  Tried that but no change. Still missing.

**Comment by Liluoai** [comment]
I have the same problem.
`LiluoaideMacBook-Pro:~ Liluoai$ sudo jupyter nbextensions_configurator enable --user
Enabling: jupyter_nbextensions_configurator
- Writing config: /Users/Liluoai/.jupyter
    - Validating...
      jupyter_nbextensions_configurator 0.4.0 OK
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Enabling tree nbextension nbextensions_configurator/tree_tab/main...`

**Comment by kraeml** [comment]
Same here. I also tried @zhiruiwang but no change.

```
pip3 freeze | grep jupyter
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
```

**Comment by kraeml** [comment]
On an other jupyter installation the nbextensions is running.

Here the output pip3 freeze:

```
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
```

I wondering jupyter-notebook version was not printed:

Here on not working:

```
jupyter-notebook --version
5.7.0
```

With working extensions:

```
jupyter-notebook --version
5.6.0
```

**Comment by mmcguffi** [comment]
Same here with 5.7.0 -- previously I had this working on a different system, which (presumably) had an older version of jupyter

**Comment by pollenjp** [comment]
@kraeml 
I found that jupyter-notebook version is printed as below.

```
$ pip3 freeze | grep notebook
notebook==5.7.0
```

In GitHub repository, jupyter-notebook installation is described below.
https://github.com/jupyter/notebook
```
$ pip install notebook
```

So, I downgrade jupyter-notebook version from 5.7.0 to 5.6.0.

```
$ pip install --user notebook==5.6.0
```

`--user` option  according to your environment

but if you pip install some PyPI package, it automatically upgrade jupyter-notebook version to 5.7.0.
Then, uninstall 5.7.0 and install 5.6.0 again.

```
$ pip uninstall notebook
($ sudo chown -R $USER:$USER ~/.local    #  if permission error, you need to run this command)
$ pip install --user notebook==5.6.0
```

Work by these in my envirnment.

**Comment by pollenjp** [comment]
You might know you can access to the nbextension configurator from a notebook.

<img width="490" alt="2018-10-03 10 26 17" src="https://user-images.githubusercontent.com/33354327/46385590-ce96a100-c6f7-11e8-88e1-c4313078b996.png">

**Comment by mazzma12** [comment]
the tab is still missing on `jupyter-notebook 5.7.0` but you can indeed access the configurator via the URL  directly : http://localhost:8888/nbextensions

**Comment by lwasser** [comment]
+1 on this issue. same thing. it is accessible via the dropdown and url but the tab is missing in notebook version 5.7

**Comment by Idodox** [comment]
+1, same issue. Can access via the direct URL, but can't see the tab on the home page. Also on 5.7.0

**Comment by thenekolite** [comment]
[jupyter-notebook 5.6.0]

![screenshot from 2018-10-09 21-48-47](https://user-images.githubusercontent.com/43208261/46677679-48092480-cc0d-11e8-9739-c069f850a135.png)

**Comment by cbolisetti** [comment]
I have the same issue: 404 : Not Found

**Comment by juhasch** [comment]
The missing configurator tab is due to a left over `jqueryui` reference.
See PR #85

**Comment by lwasser** [comment]
oh this is great that there a fix in the works! thank you @juhasch . it would be nice to see this implemented!

**Comment by VinayChaudhari1996** [comment]
How to fix it ? 

> This nbextension's require url (zenmode/main) is referenced by two different yaml files on the server. This probably means that there are two installations of the same nbextension in different directories on the server. If they are different, only one will be loaded by the notebook, and this may prevent configuration from working correctly. Check the jupyter notebook server log for the paths of the relevant yaml files.


![screenshot 88](https://user-images.githubusercontent.com/42869040/47523977-fc19d900-d8b6-11e8-8bc5-38bc5c5347b1.png)

**Comment by NJT145** [comment]
still no solution for that. i am using jupyter_nbextensions_configurator from conda-forge channel on anaconda, and still can not see the tab.

**Comment by WNoxchi** [comment]
> The missing configurator tab is due to a left over `jqueryui` reference.
> See PR #85

This just worked for me (w/ up-to-date jupyter & jupyterlab install). For anyone looking for a quick fix before this gets merged: 'jqueryui' on line 4 has to be changed to 'jquery'. You'll find the path to the file to change by clicking the PR number in @juhasch 's post, then clicking 'Files changed' on the PR page. 'src/' is the path to your nbextensions_configurator package. So if you're using a conda environment you can find that via:

path_to_conda_env/lib/pythonX.X/site-packages/

**Comment by 4Z4T4R** [comment]
Changing the `jqueryui` reference manually and restarting didn't do it for me. :rabbit2:

**Comment by Saliva520319** [comment]
> > The missing configurator tab is due to a left over `jqueryui` reference.
> > See PR #85
> 
> This just worked for me (w/ up-to-date jupyter & jupyterlab install). For anyone looking for a quick fix before this gets merged: 'jqueryui' on line 4 has to be changed to 'jquery'. You'll find the path to the file to change by clicking the PR number in @juhasch 's post, then clicking 'Files changed' on the PR page. 'src/' is the path to your nbextensions_configurator package. So if you're using a conda environment you can find that via:
> 
> path_to_conda_env/lib/pythonX.X/site-packages/
> 
> oh this is already merged? hmm maybe not on conda/PyPI yet? anyway.

not works for me

**Comment by SumNeuron** [comment]
yup

**Comment by SilvesterHsu** [comment]
I uninstall notebook(5.7.2) to install notebook(5.6.0), and then problem solved.

**Comment by juhasch** [comment]
Should be fixed in version 0.4.1. If you still have problems after the update, please open a new issue.

**Comment by ASH1998** [comment]
I know this issue is closed...but sometimes when you first twinkling the extentions you might un-click the NB-extentions edit menu checklist.
So go to [nb extentions]( http://localhost:8888/nbextensions?nbextension=nbextensions_configurator/config_menu/main) and then click the button.

**Comment by RW04** [comment]
> pip3 freeze | grep jupyter

jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0


I tried installing nbextension through conda, pip. But nothing works. May someone help me on this?

**Comment by doufuxixi123** [comment]
i use conda to install nbextensions. like following, and get problem.
    conda install -c conda-forge jupyter_nbextensions_configurator

problem describe:
there are not items to check in nbextensions configurable panel. and tell these words:
    add an edit-menu item to open the nbextensions configurator page

solving:
1/ uninstall nbextensions:
    conda uninstall jupyter_nbextensions_configurator
2/ install nbextensions via pip:
    pip install jupyter_contrib_nbextensions
    jupyter contrib nbextension install --user
    jupyter nbextension enable codefolding/main

may be the problem due to own company jupyter setting. when i download jupyter_contrib_nbextensions via pip. the package download from own company repository, not from website.

**Comment by theSuiGenerisAakash** [comment]
https://stackoverflow.com/questions/49647705/jupyter-nbextensions-does-not-appear Please check this out. Worked for 5.7.4 for me.

**Comment by StanislawAniola** [comment]
Hi, I ma using Notebook version 6.0.1

The solution that works for me: 
1. search and open Anaconda Prompt
2. type pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install
3. reopen jupiter notebook

If you will do it in basic command prompt, it will does not work.

**Comment by snehal47** [comment]
> Hi, I ma using Notebook version 6.0.1
> 
> The solution that works for me:
> 
> 1. search and open Anaconda Prompt
> 2. type pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install
> 3. reopen jupiter notebook
> 
> If you will do it in basic command prompt, it will does not work.

It works thanks for me

$ pip3 freeze | grep jupyter
jupyter-client==6.1.6
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server==0.1.1
jupyterlab==2.2.4
jupyterlab-pygments==0.1.1
jupyterlab-server==1.2.0

**Comment by Mcflyuu** [comment]
> Hi, I ma using Notebook version 6.0.1
> 
> The solution that works for me:
> 
> 1. search and open Anaconda Prompt
> 2. type pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install
> 3. reopen jupiter notebook
> 
> If you will do it in basic command prompt, it will does not work.

Thank you! It worked for me.

**Comment by sudarshan85** [comment]
None of the solutions here work for me. Here is my configuration:
```
jupyter --version
jupyter core     : 4.7.0
jupyter-notebook : 6.1.6
qtconsole        : not installed
ipython          : 7.19.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.1
nbformat         : 5.0.8
traitlets        : 5.0.5
```

```
36:jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1601311786391/work
37:jupyter-contrib-core==0.3.3
38:jupyter-contrib-nbextensions==0.5.1
39:jupyter-core @ file:///tmp/build/80754af9/jupyter_core_1606148959479/work
40:jupyter-highlight-selected-word==0.2.0
41:jupyter-latex-envs==1.4.6
42:jupyter-nbextensions-configurator==0.4.1
43:jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
44:jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
```

Could someone please help?

**Comment by saurabh3679** [comment]
try running jupyter notebook with the following command after you installed the extensions:

`jupyter notebook`

I downgraded to jupyter 5.7.10 and then installed the extensions. afterward when I ran the jupyter notebook with the above mentioned command, I got the extensions.

**Comment by phungvansyhb** [comment]
may be help :  
`jupyter contrib-nbextension install --user`  
difference is ' - '

**Comment by nity47** [comment]
cant find items in nbextensions[
![Screenshot 2021-06-08 19 19 33](https://user-images.githubusercontent.com/67295180/121273735-88257700-c88e-11eb-9a1d-8802f81dc5a2.png)
](url)

**Comment by nity47** [comment]
This is all i can see on the tab.. help pls

**Comment by statco19** [comment]
> 2\. type pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install

jupyter notebook --version == 6.4.0
it worked for me. Thanks!

**Comment by avel848895** [comment]
jupyter contrib-nbextension install --user
Worked for me Yay!

**Comment by Lexafy** [comment]
> My configurator tab also disappeared recently, but after re-executing
> 
> ```
> jupyter nbextensions_configurator enable --user
> ```
> 
> it will show up again.

Thanks, it worked for me

**Comment by Lexafy** [comment]
> My configurator tab also disappeared recently, but after re-executing
> 
> ```
> jupyter nbextensions_configurator enable --user
> ```
> 
> it will show up again.

Thanks, this worked for me

**Comment by jamesokechukwu** [comment]
i guess these codes below are to be ran on Jupyter prompt, after i did it brought out syntax errorr below each of them and the extensions is not yet added
# pip3 freeze | grep jupyter
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0

**Comment by normanrahmel** [comment]
> jupyter contrib-nbextension install --user

It also worked for me :) Thank you!

**Comment by JuanMP3** [comment]
I finally find out how to solve it. Once you get this: 
![image](https://user-images.githubusercontent.com/106283785/185757949-1ddd3109-3548-47b4-829e-f7fefd4f33fa.png)
Just close your entire notebook and all the things related to Jupyter
Re-open your notebook again and go to http://localhost:8888/nbextensions to enable it!

**Comment by Josephnwogwugwu476** [comment]
> chjch

Mine says 'jupyter-contrib-nbextension' not found


How can I go about it
