### ISSUE TITLE
Still have this issue

### ISSUE THREAD

**Issue by ipozdnyakov** [Jupyter-contrib/jupyter_nbextensions_configurator#81]
Tab "Nbextensions" doesn't appear at main dashboard
and the error in browser console:

```
Uncaught TypeError: $ is not a function
    at Object.load_ipython_extension (main.js?v=20180923225346:40)
```

_Originally posted by @ipozdnyakov in https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issue_comments#issuecomment-423843702_

**Comment by juhasch** [comment]
This should be fixed in version 0.4.1. Please open a new issue if you still encounter this problem after updating.
