### ISSUE TITLE
My table view i.e df.head() is not working

### ISSUE THREAD

**Issue by kzk32** [Jupyter-contrib/jupyter_nbextensions_configurator#88]
Hi,

when I want to view **df.head()** nothing prints as results. This only happened after I played around with the new nbextention in my jupyter. I have tried ticking and unticking multiple option but I stilll have nothing showing. HELP PLEASE!!!!

kzkn

**Comment by juhasch** [comment]
If you still have this problem and it relates with the nbextensions_configurator, please open a new issue and describe your problems with the nbextensions_configurator extension.
