### ISSUE TITLE
Upload 0.4.1 on PyPi

### ISSUE THREAD

**Issue by juhasch** [Jupyter-contrib/jupyter_nbextensions_configurator#93]
Hey @jcb91, I can't update the configurator on PyPi. Could you do that or give me rights ?

**Comment by jcb91** [comment]
Ah thanks for fixing this @juhasch, and apologies for my absence of late :( I think I've added you as a maintainer on pypi, which should do it, I think. Best wishes for the coming new year!

**Comment by juhasch** [comment]
Thanks for the prompt help. No worries :smile:, and best wishes for you, too

**Comment by flying-sheep** [comment]
Hi! I’m packaging this for Arch, but rely on the wheel.

Could you please upload a wheel as well?
