### ISSUE TITLE
Not able to see the jupyter_nbextensions_configurator

### ISSUE THREAD

**Issue by EnricowithR** [Jupyter-contrib/jupyter_nbextensions_configurator#94]
I upgraded jupyter_nbextensions_configurator to 0.4.1
then I run again: 
jupyter nbextensions_configurator enable --user

However at the following page:
http://localhost:8888/tree
the extensions is not visible yet.

Also if I try to access to
http://localhost:8888/custom/base/url/nbextensions
or
http://localhost:8888/custom/base/url/tree
it returns:
404 : Not Found
You are requesting a page that does not exist!

What can be done to make it visible?

**Comment by juhasch** [comment]
The standard url is http://localhost:8888/nbextensions, unless you habe changed the `baseurl` configuration. Did you try that ?

**Comment by EnricowithR** [comment]
I tried it and it gives the same not found error

**Comment by juhasch** [comment]
Do you see `[jupyter_nbextensions_configurator] enabled 0.4.1` in the log when starting the notebook ?

**Comment by juhasch** [comment]
1. try `python -c "import jupyter_nbextensions_configurator"`. If you get an error, the configurator is not installed.
2. try `jupyter-serverextension  list`. It should look like this:
```
config dir: /home/juhasch/.jupyter
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
```
If not, the extension was not installed properly. 

You might want to create a new virtualenv or conda environment (depending on your installation) and try reinstalling in a fresh setup.

**Comment by EnricowithR** [comment]
1. the first command returns:
No module named 'jupyter_nbextensions_configurator'

2. and the second one returns:
jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
config dir: /anaconda3/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 0.27.0 OK

How is it possible that the extension appears as enabled but the module is not found?

**Comment by juhasch** [comment]
You likely installed the configurator package in your base environment and not in your current one.

**Comment by EnricowithR** [comment]
Right, that was the case. I fixed it following the suggestions from here:
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1115
