### ISSUE TITLE
configurator tab not appearing

### ISSUE THREAD

**Issue by ggrrll** [Jupyter-contrib/jupyter_nbextensions_configurator#96]
Hi, 

thanks gain for the nice extension.

I have currently issue: the configurator is not showing at all (http://localhost:8888/nbextensions gives 404 and it's not present as well in the edit menu of notebooks) -- please find attached the screenshot of my browser (safari 12.0.3)

![screenshot 2019-02-27 at 11 37 05](https://user-images.githubusercontent.com/15370425/53484515-489f3c00-3a84-11e9-8cbb-f89f37411404.png)

ps: my settings

- `notebook` 5.7.4
- `jupyter_nbextensions_configurator` 0.4.1
- mac os 10.14

**Comment by ggrrll** [comment]
ok, I might have a problem with the versions:

 `pip show jupyter_nbextensions_configurator` gives
 `Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
`
but 
 `which jupyter` returns `/Library/Frameworks/Python.framework/Versions/3.6/bin/jupyter
`

indeed `jupyter nbextensions_configurator enable --system` tells me that I have the version `0.4.0` , 
but 
 `pip show jupyter_nbextensions_configurator` gives `0.4.1` ...

**Comment by jedmitten** [comment]
I have a similar issue. I have no `nbextensions` tab nor can I navigate there directly. I use `notebook` frequently but am just getting started with extensions and the configurator.
Mac: 10.13.6 (High Sierra)
```bash
$ jupyter notebook --version
5.6.0
```
```bash
$ python3 --version
Python 3.6.8rc1
```

```bash
$ pip3 show jupyter_nbextensions_configurator
Name: jupyter-nbextensions-configurator
Version: 0.4.1
Summary: jupyter serverextension providing configuration interfaces for nbextensions.
Home-page: https://github.com/jupyter-contrib/jupyter_nbextensions_configurator
Author: jcb91, jupyter-contrib developers
Author-email: joshuacookebarnes@gmail.com
License: BSD 3-clause
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: jupyter-contrib-core, jupyter-core, notebook, pyyaml, tornado, traitlets
Required-by: jupyter-contrib-nbextensions
```

```bash
$ which jupyter
/Library/Frameworks/Python.framework/Versions/3.6/bin/jupyter
```

**Comment by ggrrll** [comment]
Thanks @jedmitten  for your and sharing your case

I didn't get if/how this can help me though 🤔  ...(I never mentioned `pip3`) I had `jupyter_nbextensions_configurator` insatalled via `pip` -- and not other versions ... (if that's your point...)

**Comment by jedmitten** [comment]
@ggrrll I wanted to make sure I showed my own path to solving a similar error just in case it helped you with yours. Good luck!

**Comment by ggrrll** [comment]
of course! thanks again -- I wanted just to make sure I understood correctly

**Comment by moriakijp** [comment]
I had the same problem, but I solved it in the following way.
Entered global with `--sys-prefix`, but when operating under`/home`, should be entered there instead of global in the following way.
`jupyter-nbextension install rise --py  --user`
`jupyter-nbextension enable rise --py  --user`

**Comment by rgimenes26** [comment]
The same was happening with me. Cant figure out why. 
Was trying install  with pip first. Than switched to conda one line installation and worked. 

`conda install -c conda-forge jupyter_contrib_nbextensions`

**Comment by ggrrll** [comment]
I am closing, as I am not any longer on mac os -- and, as far as I can remember the issues was solved
